# Generated by Django 5.0.3 on 2024-03-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_productdetails_pvendorname_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
