# Generated by Django 5.0.3 on 2024-03-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Pcatagory',
        ),
    ]
