# Generated by Django 5.0.3 on 2024-03-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_catagory_pcatagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pcatagory',
            new_name='Catagory',
        ),
        migrations.RenameField(
            model_name='catagory',
            old_name='CatagoryName',
            new_name='cat_name',
        ),
    ]
